---
apiVersion: ec2.aws.crossplane.io/v1beta1
kind: Subnet
metadata:
  name: subnet-a
spec:
  forProvider:
    cidrBlock: 172.31.1.0/24
    vpcId: vpc-002c8d8307a98f7f5
    availabilityZone: eu-north-1a
    region: eu-north-1
  providerRef:
    name: aws-provider
---
apiVersion: ec2.aws.crossplane.io/v1beta1
kind: Subnet
metadata:
  name: subnet-b
spec:
  forProvider:
    cidrBlock: 172.31.2.0/24
    vpcId: vpc-002c8d8307a98f7f5
    availabilityZone: eu-north-1b
    region: eu-north-1
  providerRef:
    name: aws-provider
---
apiVersion: ec2.aws.crossplane.io/v1beta1
kind: Subnet
metadata:
  name: subnet-c
spec:
  forProvider:
    cidrBlock: 172.31.3.0/24
    vpcId: vpc-002c8d8307a98f7f5
    availabilityZone: eu-north-1c
    region: eu-north-1
  providerRef:
    name: aws-provider
---
apiVersion: database.aws.crossplane.io/v1beta1
kind: DBSubnetGroup
metadata:
  name: sample-subnet-group
spec:
  forProvider:
    description: sample group
    region: eu-north-1
    subnetIdRefs:
      - name: subnet-a
      - name: subnet-b
      - name: subnet-c
  providerRef:
    name: aws-provider
